# permissions for end users to edit pretzelais.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pretzelai-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pretzelai-operator
    app.kubernetes.io/part-of: pretzelai-operator
    app.kubernetes.io/managed-by: kustomize
  name: pretzelai-editor-role
rules:
- apiGroups:
  - pretzelai.pretzelai.local
  resources:
  - pretzelais
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pretzelai.pretzelai.local
  resources:
  - pretzelais/status
  verbs:
  - get
