apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pretzelai-controller-manager-binding
subjects:
  - kind: ServiceAccount
    name: pretzelai-controller-manager
    namespace: default
  - kind: ServiceAccount
    name: pretzelai-controller-manager
    namespace: system
roleRef:
  kind: ClusterRole
  name: manager-role
  apiGroup: rbac.authorization.k8s.io
