apiVersion: v1
kind: ServiceAccount
metadata:
  name: pretzelai-controller-manager
  namespace: default

---
# ServiceAccount for operator running in `system` namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pretzelai-controller-manager
  namespace: system
