apiVersion: v1
kind: Service
metadata:
  name: pretzelai-<CR_NAME>-svc
  namespace: <CR_NAMESPACE>
  labels:
    app: pretzelai
    pretzelai_cr: <CR_NAME>
spec:
  type: <SERVICE_TYPE>
  selector:
    app: pretzelai
    pretzelai_cr: <CR_NAME>
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
