---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.10.0
  creationTimestamp: null
  name: pretzelais.pretzelai.pretzelai.local
spec:
  group: pretzelai.pretzelai.local
  names:
    kind: PretzelAI
    listKind: PretzelAIList
    plural: pretzelais
    singular: pretzelai
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The desired number of replicas
      jsonPath: .spec.replicas
      name: Replicas
      type: integer
    - description: The number of ready replicas
      jsonPath: .status.readyReplicas
      name: Ready
      type: integer
    - description: The service type
      jsonPath: .spec.serviceType
      name: Service
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: PretzelAI is the Schema for the pretzelai API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: PretzelAISpec defines the desired state of PretzelAI
            properties:
              configMapName:
                description: ConfigMapName is the optional name of a ConfigMap containing
                  configuration files.
                type: string
              image:
                description: Image allows overriding the container image used for
                  PretzelAI. If not specified, the operator uses the default image.
                type: string
              replicas:
                default: 1
                description: Replicas defines the desired number of PretzelAI pods
                  to run.
                format: int32
                minimum: 1
                type: integer
              serviceType:
                default: ClusterIP
                description: ServiceType specifies how to expose the application (ClusterIP,
                  NodePort, LoadBalancer).
                enum:
                - ClusterIP
                - NodePort
                - LoadBalancer
                type: string
            type: object
          status:
            description: PretzelAIStatus defines the observed state of PretzelAI
            properties:
              availableReplicas:
                description: AvailableReplicas is the total number of available pods.
                format: int32
                type: integer
              configMapStatus:
                description: ConfigMapStatus confirms if the referenced ConfigMap
                  was found and applied.
                type: string
              readyReplicas:
                description: ReadyReplicas is the number of pods that are currently
                  ready and serving traffic.
                format: int32
                type: integer
              serviceStatus:
                description: ServiceStatus reports the current type/status of the
                  Service.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
